project:
  type: website

website:
  favicon: images/favicon.ico
  open-graph: 
    site-name: "mdwm"
  site-url: https://mdwm.org/
  search: false
  navbar:
    # logo: images/mdwm-skiwar.png
    # logo: images/mdwm-dark.png
    logo: images/logo.webp
    logo-alt: "marten's blog"
    # title: "mdwm"
    collapse-below: lg
    right: 
      - text: "martenw.com →"
        href: https://martenw.com
    left:
      - text: "← home"
        href: ./
  page-navigation: true
  back-to-top-navigation: false
  page-footer:
    left: 
      - text: "© 2024-2026 "
    right:
      - href: about.qmd
        text: about

format:
  html:
    theme: [pressmark.scss]
    toc: true
    toc-location: body
    grid:
      body-width: 650px
      sidebar-width: 450px
      margin-width: 200px
      # gutter-width: 0em
    html-math-method: katex
    

link-external-icon: false
link-external-newwindow: true
